/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CDeus_abi } from "./CDeus_abi";
export * as factories from "./factories";
export { CDeus_abi__factory } from "./factories/CDeus_abi__factory";
